server:
  port: 9087
spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/log_in?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 985263
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000